# Generated by Django 4.2.6 on 2024-05-05 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('def_rans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_identificar',
            name='incidente',
            field=models.IntegerField(choices=[[0, 'Toma las decisiones sobre como actuar'], [1, 'Lo reporta ante un directivo para obtener el plan de acción'], [2, 'Depende de un tercero que le brinda servicios de seguridad para actuar ante el incidente'], [3, 'Otro']], verbose_name='En el caso de un incidente de segurdad informática (ataque por viruso informático u otras formas) usted: '),
        ),
        migrations.AlterField(
            model_name='model_identificar',
            name='rol',
            field=models.IntegerField(choices=[[0, 'Administrativo'], [1, 'Directivo'], [2, 'Servicio'], [3, 'Sistemas/Informática/TICs'], [4, 'Soporte'], [5, 'Otro']], verbose_name='¿Cuál es su puesto/rol en su organización?'),
        ),
        migrations.CreateModel(
            name='RespuestasIdentificar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.PositiveIntegerField(blank=True, null=True, verbose_name='Respuesta')),
                ('pregunta', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
