# Generated by Django 4.2.6 on 2024-05-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_rans', '0002_alter_model_identificar_incidente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestasidentificar',
            name='pregunta',
            field=models.TextField(blank=True, null=True, verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='respuestasidentificar',
            name='respuesta',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta'),
        ),
    ]
