# Generated by Django 4.2.6 on 2024-05-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_rans', '0003_alter_respuestasidentificar_pregunta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_identificar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empresa', models.IntegerField(choices=[[0, 'Empresa Local (PyME)'], [1, 'Empresa Nacional (Privada o Pública)'], [2, 'Empresa Multinacional (Con Servicios Fuera de México)'], [3, 'Empresa Transnacional o Internacional'], [4, 'Otro']], verbose_name='¿Cuál es el tipo de tu empresa?')),
                ('rol', models.IntegerField(choices=[[0, 'Empresa Local (PyME)'], [1, 'Empresa Nacional (Privada o Pública)'], [2, 'Empresa Multinacional (Con Servicios Fuera de México)'], [3, 'Empresa Transnacional o Internacional'], [4, 'Otro']], verbose_name='¿Cuál es su puesto/rol en su organización?')),
                ('incidente', models.IntegerField(choices=[[0, 'Empresa Local (PyME)'], [1, 'Empresa Nacional (Privada o Pública)'], [2, 'Empresa Multinacional (Con Servicios Fuera de México)'], [3, 'Empresa Transnacional o Internacional'], [4, 'Otro']], verbose_name='En el caso de un incidente de segurdad informática (ataque por viruso informático u otras formas) usted: ')),
            ],
        ),
        migrations.AlterField(
            model_name='model_identificar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
