# Generated by Django 4.2.6 on 2024-05-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_rans', '0005_alter_model_identificar_incidente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_identificar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
