# Generated by Django 4.2.6 on 2024-05-07 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('def_rans', '0006_alter_model_identificar_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_herramientas',
            old_name='sdsdp',
            new_name='sgsdp',
        ),
        migrations.CreateModel(
            name='RespuestasHerramientas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField(blank=True, null=True, verbose_name='Respuesta')),
                ('pregunta', models.TextField(blank=True, null=True, verbose_name='Pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestasConciencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField(blank=True, null=True, verbose_name='Respuesta')),
                ('pregunta', models.TextField(blank=True, null=True, verbose_name='Pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
